### ISSUE TITLE
Error: data: Hex number must contain 0x and at least one hex digit;

### ISSUE THREAD

**Issue by TheoXD** [pipermerriam/ethereum-grove#11]
When trying to run the contract in a sandbox I get this:

`Error: data: Hex number must contain 0x and at least one hex digit;`

Maybe project needs to be updated?

**Comment by TheoXD** [comment]
Apparently since I wasn't trying to deploy but rather inherit from Grove contract, I had to change some "public" function to "internal" whenever "Index storage index" was used as a function argument.

**Comment by pipermerriam** [comment]
Yes, Grove is intended to be used as a Library so you'll have to make modifications if you want to inherit from it.
